# Generated by Django 5.0.4 on 2024-04-29 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_chat_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_type',
            field=models.IntegerField(choices=[(0, 'Private'), (1, 'Group')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='usertochat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_chat', to='app.chat'),
        ),
        migrations.AlterField(
            model_name='usertochat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_to_chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
